language: r
cache: packages
sudo: false
warnings_are_errors: false
git:
  depth: false
install:
  - Rscript install-packages.R
  
script:
  - Rscript datascript.R
  - Rscript archive.R

after_success:

